apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uvgo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-uvgo@sha256:26154d0dfbece2cfd44678698d30e6f50737a38be4a878b69ef4e122fe475e35
        name: my-nodejs
        resources: {}
status: {}
